### ISSUE TITLE
a

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/phuslu.github.io#15]
![6bc4312d03fae1de97a2dd03885f4c86_hd](https://user-images.githubusercontent.com/13601611/34649228-af62b2a0-f3e5-11e7-8dab-0b551e61de1f.jpg)

**Comment by zzhhbyt1** [comment]
怪了，这个数本来就等于1啊，为什么一通乱算然后还贴个暴漫表情发在老大这里。。。。

**Comment by sundaqing1969** [comment]
随便发的
