### ISSUE TITLE
通缉令

### ISSUE THREAD

**Issue by wangjingzhuaren** [phuslu/phuslu.github.io#2]
Phus Lu ：
　　你长期与反华势力狼狈为奸，已经违反相关法律与规定。公安部技术侦察组现已定位你的网络IP地址，限你于3日内到户籍所在地公安局或民政局投案自首，争取宽大处理，否则后果自负！

　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　南京市公安局
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　2017年9月9日

**Comment by dou4cc** [comment]
@phuslu close
