### ISSUE TITLE
如何改成点击标题栏文件名跳转对应目录?

### ISSUE THREAD

**Issue by qokelate** [phuslu/phuslu.github.io#21]
例如 **Index of /LEDE/ledeBuild/targets/x86/generic/** 能否实现点击文件跳转对应目录?

**Comment by qokelate** [comment]
补充一下, 是`autoindex.html`这个文件对应的美化功能

**Comment by phuslu** [comment]
我试下

**Comment by phuslu** [comment]
在 nginx 下应该可以了 https://github.com/phuslu/phuslu.github.io/commit/967a176b66f48bd850ece96f604a7c512f29dc06
