### ISSUE TITLE
添加配置文件后根目录列表显示空白

### ISSUE THREAD

**Issue by cooper1x** [phuslu/phuslu.github.io#22]
我的Nginx版本是1.11.5，我按照你的这篇教程做了，但是显示的页面是空白的，请问怎么解决这个问题呢？
https://www.91yunbbs.com/discussion/441/autoindex-html-%E4%B8%80%E8%A1%8C%E9%85%8D%E7%BD%AE%E7%BE%8E%E5%8C%96-nginx-%E7%9B%AE%E5%BD%95%E6%88%90-github-%E9%A3%8E%E6%A0%BC

**Comment by phuslu** [comment]
方便给出你的网站地址吗，我帮你来看下。

**Comment by cooper1x** [comment]
@phuslu 我的是本地用的呢，可以留下你的QQ吗？我给你发邮件了

**Comment by phuslu** [comment]
啊，没有 qq 号。。。

**Comment by cooper1x** [comment]
@phuslu 可以远程帮我看下吗，我给你发过邮件了，用TeamViewer
