### ISSUE TITLE
大佬，请问node.js写的动态网站应该如何配置这个优化文件呢？

### ISSUE THREAD

**Issue by siriusfinex** [phuslu/phuslu.github.io#23]
我的网站主站是动态网站，现在新增了几个二级路径的文件索引目录，想给这几个索引目录美化一下，根目录找不到，随机生成的，请问能该怎么配置autoindex.html呢？

**Comment by phuslu** [comment]
nodejs 这么做。

1.  把 autoindex.html 加载到内存中。
2.  访问索引页时候用 node 自动声称一个简单的列表。
3.  然后把 autoindex.html 拼接在后面。
4. 发给客户端。

具体请看样例 https://phuslu.github.io/topic/ （右键查看源码即可）

**Comment by siriusfinex** [comment]
谢谢大佬的指点。
