### ISSUE TITLE
报错Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by cooper1x** [phuslu/phuslu.github.io#25]
```
(index):152 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at insert ((index):152)
    at (index):184
    at (index):222
```
使用这个文件后出现报错，可能是我有中文目录吧，貌似是转义的问题，请问怎么解决呢？
152行代码如下：
`displayname = decodeURIComponent(filename.replace(/\/$/, ''))`

**Comment by cooper1x** [comment]
```
var result = filename.replace(/\/$/, '')
            try {
                displayname = decodeURIComponent(result);
            }
            catch (ex) {
                displayname = unescape(result);
            }
```
![image](https://user-images.githubusercontent.com/9080789/45477157-7fea8c80-b773-11e8-999f-1d91e0a72f68.png)

我修改成这样就可以进去了，但是中文目录是乱码的，请问怎么解决呢？
另外中文的文件点击也是报错页面打不开，有办法解决吗？
![image](https://user-images.githubusercontent.com/9080789/45477165-87aa3100-b773-11e8-9f3a-f1846401aaf7.png)

**Comment by phuslu** [comment]
Linux 中文目录是支持的。请检查一下是不是这些配置不对

1. nginx.conf 设置了 charset utf-8
2. linux 文件系统编码是 utf-8

**Comment by cooper1x** [comment]
```
# download autoindex.html to /wwwroot
location ~ ^(.*)/$ {
    charset utf-8;
    autoindex on;
    autoindex_localtime on;
    autoindex_exact_size off;
    add_after_body /autoindex.html;
}
```
我是在Windows下用的Nginx，配置写了UTF-8的。

**Comment by phuslu** [comment]
windows 不行，因为 nginx 用的是 windows 的 ANSI(mbcs) 的编码的 API

你尝试把 nginx.conf 的 charset gbk 试下。

**Comment by cooper1x** [comment]
试过了不行呢。。。

**Comment by phuslu** [comment]
那应该和 autoindex.html 关系不大了。你应该尝试在没有 add_body_after /autoindex.html 的情况下先修复乱码问题。

**Comment by cooper1x** [comment]
autoindex如果我不加那个try，直接是空白的不能显示……
目前就是显示乱码问题
