### ISSUE TITLE
autoindex.html 文件夹文字过长 识别为文件而非文件夹

### ISSUE THREAD

**Issue by mengyyy** [phuslu/phuslu.github.io#3]
请问能调整文件夹识别长度么

**Comment by phuslu** [comment]
这个问题貌似已经修复过一次了，我这边已经不出现了。

能给出样例么？

**Comment by mengyyy** [comment]
这长度看着很有强迫症……

![snipaste_2017-09-21_16-30-18](https://user-images.githubusercontent.com/10589755/30686245-32b44084-9eea-11e7-9833-1666702df98b.png)

**Comment by phuslu** [comment]
哦，这个长度是 nginx 的 autoindex 模块决定的，autoindex.html 只能重新渲染一下，并不能还原成原始文件名。

**Comment by phuslu** [comment]
我尝试看下 json 是否是能得到原始文件名

**Comment by phuslu** [comment]
可以修复，我来看看.

**Comment by mengyyy** [comment]
多谢大佬～～～不行我也是服气的～

**Comment by phuslu** [comment]
已经修复。

通过修改 https://github.com/phuslu/phuslu.github.io/blob/master/autoindex.html#L5 这个选项，可以改变最大文件名。比如改成 1024 应该就能绝大部分文件名字 :D

**Comment by mengyyy** [comment]
确认可以了 
![snipaste_2017-09-21_17-15-42](https://user-images.githubusercontent.com/10589755/30688366-8641a02e-9ef0-11e7-867a-b4dfb40a5808.png)
