### ISSUE TITLE
探针页面顶部提示这个如何解决呢？

### ISSUE THREAD

**Issue by Mentire** [phuslu/phuslu.github.io#31]
Warning: Invalid argument supplied for foreach() in /www/wwwroot/123458.xyz/index.php on line 270

Warning: is_file(): open_basedir restriction in effect. File(/sys/class/dmi/id/bios_vendor) is not within the allowed path(s): (/www/wwwroot/123458.xyz/:/tmp/:/proc/) in /www/wwwroot/123458.xyz/index.php on line 291

Warning: is_file(): open_basedir restriction in effect. File(/sys/class/dmi/id/board_name) is not within the allowed path(s): (/www/wwwroot/123458.xyz/:/tmp/:/proc/) in /www/wwwroot/123458.xyz/index.php on line 297

Warning: is_file(): open_basedir restriction in effect. File(/sys/class/dmi/id/product_name) is not within the allowed path(s): (/www/wwwroot/123458.xyz/:/tmp/:/proc/) in /www/wwwroot/123458.xyz/index.php on line 301

Warning: is_dir(): open_basedir restriction in effect. File(/dev/disk/by-id) is not within the allowed path(s): (/www/wwwroot/123458.xyz/:/tmp/:/proc/) in /www/wwwroot/123458.xyz/index.php on line 307

**Comment by phuslu** [comment]
这是因为机器上php环境禁用了一些函数，我尝试（兼容）处理一下。

**Comment by phuslu** [comment]
去掉 glob 和 is_file 两个函数的使用，应该可以了。
