### ISSUE TITLE
请问如何给页面添加小图标？

### ISSUE THREAD

**Issue by otherbanana** [phuslu/phuslu.github.io#32]
请教一下大佬，看了之前的提问，知道了怎么改页面标题，但是我想加个小图标要怎么加呢？

**Comment by phuslu** [comment]
图标是使用 svg + css 实现的，见 autoindex.html 代码的最底部。
这个 css 剥离自 github octicon, 我放了一份在 https://github.com/phuslu/phuslu.github.io/blob/master/history/octicons.css

**Comment by otherbanana** [comment]
不好意思大佬，可能是我没有表述清楚。我指的是这个小图标
![TIM截图20200103102318](https://user-images.githubusercontent.com/34509569/71704115-55628e00-2e13-11ea-9077-e2d1ebfb5a5b.png)

**Comment by phuslu** [comment]
直接在网站根目录放一个favicon.ico文件即可。

https://github.com/phuslu/phuslu.github.io/blob/master/favicon.ico
