### ISSUE TITLE
探针速度检测错误

### ISSUE THREAD

**Issue by YuutaDoNo** [phuslu/phuslu.github.io#35]
系统版本: Debian GNU/Linux 10 (buster)
nginx信息: nginx/1.16.1 php/7.3.14-1~deb10u1
php信息: 7.3.14-1~deb10u1
CPU型号: ARMv7 Processor rev 1 (v7l)

错误描述: 在上传/下载速度超过某个值后，无法正确的显示网速。但流量统计正常运行。
已知无法显示 30MB/s 可以正常显示 600kb/s。

**Comment by phuslu** [comment]
啊，没试过这么高的速度，我看看。

**Comment by phuslu** [comment]
尝试修复了下，用服务器返回的两个时间点算出 duration
