### ISSUE TITLE
默认逆序怎么改呢？就是一出来按name排序但是z在最上面，a在最下面？

### ISSUE THREAD

**Issue by wedojava** [phuslu/phuslu.github.io#36]
如题，因为我做了个小程序，他们每次要看最新的更新信息都要点下排序，我想实现默认就是名字序号大的在最上面怎么改？改那一块呢？谢谢能赐教，没搞过nodejs，js懂一点。

**Comment by phuslu** [comment]
在结束的时候 L159 行，settimeout + sortby 试下

**Comment by wedojava** [comment]
你好，没懂你的意思，怎么 `settimeout + sortby` ?直接在那个 `}` 前写 `settimeout + sortby` ？我没成功 @phuslu
