### ISSUE TITLE
html文件无法打开

### ISSUE THREAD

**Issue by AlexYangYH** [phuslu/phuslu.github.io#37]
我在子目录用了autoindex, 显示正常，但是子目录的子目录里如果有html文件，则全部加上了autoindex里的代码，无法正常打开网页。

怎样设置可以只针对目录才加代码，而不影响正常html文件。

那个md也是，导致所有的md文件都增加了代码

**Comment by phuslu** [comment]
```nginx
location ~ ^(.*)/$ {
    charset utf-8;
    autoindex on;
    autoindex_localtime on;
    autoindex_exact_size off;
    add_after_body /autoindex.html;
}
```
注意 /$ 表示只针对目录。

**Comment by frankang** [comment]
如果仅针对单个目录添加autoindex.html，且设置了alias，请问怎么样排除里面的html文件呢？

**Comment by phuslu** [comment]
能否贴出你的 nginx.conf 添加 autoindex.html 的片段？
