### ISSUE TITLE
顶部导航栏不能切到根目录，能否再改进下

### ISSUE THREAD

**Issue by fengchen-github** [phuslu/phuslu.github.io#38]
首先感谢作者的无私付出，能使用您的作品不胜荣幸
在使用中发现顶部导航最多只能切到根目录下的一级目录，能否再改进下

**Comment by phuslu** [comment]
太客气。我更新修改了。请使用最新的 https://phus.lu/autoindex.html 即可。

**Comment by fengchen-github** [comment]
感谢
txt文本gb2312编码的查看乱码能修复吗

**Comment by phuslu** [comment]
从原理上将，这个 autoindex.html 无法对 txt 打开时候施加影响。没办法。
