### ISSUE TITLE
中文文件夹目录显示乱码

### ISSUE THREAD

**Issue by samtao** [phuslu/phuslu.github.io#4]
中文文件夹目录显示乱码！能解决么

**Comment by samtao** [comment]
![image](https://user-images.githubusercontent.com/11850977/30773432-f99a93f6-a0a2-11e7-8c48-3dc4db2afb51.png)

**Comment by phuslu** [comment]
不能复现。

推测和 nginx 有关，你把 linux locale 改成 UTF-8, 然后再 nginx.conf 加入上  `charset utf-8;` 看看

**Comment by phuslu** [comment]
测试了一下，在 nginx.conf 拿掉 `charset utf-8;` 的确就乱码了。。。

**Comment by samtao** [comment]
是的，我再nginx.conf server里加入charset utf-8 后就正常了，谢谢你
