### ISSUE TITLE
关于cmdhere.cmd的问题请教

### ISSUE THREAD

**Issue by Remonli** [phuslu/phuslu.github.io#40]
您好，无意中发现  https://phus.lu/cmdhere.cmd, 试了一下很好用，但是代码有点问题请教：

前面行似乎是调整Windows的优化设置，跟右键菜单cmd没什么关系？
```
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v "SwapfileControl" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Microsoft\Command Processor" /v "DisableUNCCheck" /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Microsoft\Command Processor" /v "PathCompletionChar" /t REG_DWORD /d 64 /f
reg add "HKLM\SOFTWARE\Microsoft\Command Processor" /v "CompletionChar" /t REG_DWORD /d 9 /f
```
接下来三行是设置终端参数没什么疑问，再后面分三部分写注册表有点不太明白作用. 
```
ver | findstr /r "5\."  ......
ver | findstr /r "6\."  ......
ver | findstr /r "10\."  ......
```
第一部分,运行了之后我到对应的注册表项找不到HKCR\Folder\shell\DOS 键。 第二部分和第三部分似乎重复了，后者只是
设置了Unicode page？

抱歉因为我对cmd操作注册表不太懂，代码也没有注释，所以只能来这里求助，希望能得到回复，谢谢！

**Comment by phuslu** [comment]
1. SwapfileControl 我去掉了，的确没什么关系。
2. DisableUNCCheck PathCompletionChar CompletionChar 是提高 cmd 的路径易用性的，我保留了。
3. `ver | findstr` 使用来判断 XP, Win7/Win8, 和 Win10 的，因为这个脚本是我从 XP 时代就开始维护的。DOS 这个是 XP 特有的。Win10 只需要关注第三个部分。
4. 的确重复，但是是为了分别处理 Win7/8 和 Win10 的不同情况。
5. `echo %~d0 | findstr ":"` 这个是为了判断用户是把 cmd.exe 保存为本地文件再运行还是直接把这些代码粘贴到 cmd.exe 直接运行。

**Comment by Remonli** [comment]
感谢回复！另外问一下能不能用这个办法启动Windows terminal？我试着用这个脚本改成启动wt.exe，但是没成功，
一直不会自动改变到当前目录，windows 商店安装的terminal 倒是直接在右键建立了一个普通权限的启动项。

也顺便推荐一下Windows terminal，这个终端非常漂亮，速度也快，建议试试。

**Comment by phuslu** [comment]
`reg add "HKCR\Directory\Background\shell\runas\command" /v "" /t REG_SZ /d "cmd.exe /d /s /k ver && cd /d %v" /f`

可以尝试改为

`reg add "HKCR\Directory\Background\shell\runas\command" /v "" /t REG_SZ /d "cmd.exe /d /s /k cd /d %v && wt.exe" /f`

思路就是先启动有管理权限的 cmd.exe 然后 cd 到对应目录启动 wt.exe ， 我目前还在用 win 8.1 暂时无法尝试 windows terminal

**Comment by Remonli** [comment]
试了一下不行，暂时不管它了，谢谢！
