### ISSUE TITLE
下载的md文件都在最后添加上了markdown.html中的代码

### ISSUE THREAD

**Issue by WittonBell** [phuslu/phuslu.github.io#41]
发现了这个项目，非常感谢作者。但是有如题的问题，怎样才能让md文件既能显示渲染成的html，又能在下载时得到的是原来的源文件？
第二个，如果能让autoindex.html和markdown.html不在root目录下，就好了，虽然可以使用前面加点的方式隐藏。

**Comment by phuslu** [comment]
下载是指用命令行(curl/wget)下载还是浏览器chrome另存为？
前者可以用 nginx.conf 加上识别 user-agent 的代码，决定是否添加markdow.html
后者在可以渲染 md 文件时候加一个下载连接，走 javascript blob 这种机制能实现原始文件的下载。

**Comment by phuslu** [comment]
> 能让autoindex.html和markdown.html不在root目录下，就好了，虽然可以使用前面加点的方式隐藏。

这个改 nginx.conf 的 add_after_body 就能做到啊

**Comment by WittonBell** [comment]
> 下载是指用命令行(curl/wget)下载还是浏览器chrome另存为？ 前者可以用 nginx.conf 加上识别 user-agent 的代码，决定是否添加markdow.html 后者在可以渲染 md 文件时候加一个下载连接，走 javascript blob 这种机制能实现原始文件的下载。

浏览器另存为:
![image](https://user-images.githubusercontent.com/8215947/168416274-b8e530d9-ca08-41e9-8291-b99a5931267f.png)

两种方式如何配置？不太懂，研究半天了，求示例。

**Comment by WittonBell** [comment]
> > 能让autoindex.html和markdown.html不在root目录下，就好了，虽然可以使用前面加点的方式隐藏。
> 
> 这个改 nginx.conf 的 add_after_body 就能做到啊

求示例，研究半天了，还是没搞明白，小白。

**Comment by WittonBell** [comment]
我看Issue #39 提到不支持中文文件名，我在Windows下使用确实有这样的问题，Linux下没问题。Windows下问题出在

```js
displayname = decodeURIComponent(filename.replace(/\/$/, ''))
```

decodeURIComponent时出错了。

**Comment by WittonBell** [comment]
> > 下载是指用命令行(curl/wget)下载还是浏览器chrome另存为？ 前者可以用 nginx.conf 加上识别 user-agent 的代码，决定是否添加markdow.html 后者在可以渲染 md 文件时候加一个下载连接，走 javascript blob 这种机制能实现原始文件的下载。
> 
> 浏览器另存为: ![image](https://user-images.githubusercontent.com/8215947/168416274-b8e530d9-ca08-41e9-8291-b99a5931267f.png)
> 
> 两种方式如何配置？不太懂，研究半天了，求示例。

列表中Name栏中保持提供原始内容链接，后面再加一列针对markdown的html浏览的链接（加了markdown.html内容），这样下载，浏览两不误，不知是否可行？感谢！

**Comment by phuslu** [comment]
> 我看Issue #39 提到不支持中文文件名，我在Windows下使用确实有这样的问题，Linux下没问题。Windows下问题出在
> 
> ```js
> displayname = decodeURIComponent(filename.replace(/\/$/, ''))
> ```
> 
> decodeURIComponent时出错了。

这个可能把 charset utf8; 改成 charset gbk; 就好了

**Comment by phuslu** [comment]
> > > 下载是指用命令行(curl/wget)下载还是浏览器chrome另存为？ 前者可以用 nginx.conf 加上识别 user-agent 的代码，决定是否添加markdow.html 后者在可以渲染 md 文件时候加一个下载连接，走 javascript blob 这种机制能实现原始文件的下载。
> > 
> > 
> > 浏览器另存为: ![image](https://user-images.githubusercontent.com/8215947/168416274-b8e530d9-ca08-41e9-8291-b99a5931267f.png)
> > 两种方式如何配置？不太懂，研究半天了，求示例。
> 
> 列表中Name栏中保持提供原始内容链接，后面再加一列针对markdown的html浏览的链接（加了markdown.html内容），这样下载，浏览两不误，不知是否可行？感谢！

这种右键另存为做不到。一个退一步的实现方式是在渲染的页面加一个下载连接。

**Comment by WittonBell** [comment]
> > 能让autoindex.html和markdown.html不在root目录下，就好了，虽然可以使用前面加点的方式隐藏。
> 
> 这个改 nginx.conf 的 add_after_body 就能做到啊

搞定，谢谢

**Comment by phuslu** [comment]
不客气。
