### ISSUE TITLE
看老大还在活动 应该问题不大

### ISSUE THREAD

**Issue by lndnxp** [phuslu/phuslu.github.io#7]
goproxy还会继续吗 还是另起炉灶 抑或无限期搁置..
隔壁xx-net的ip都给封光了,论坛里一片热闹
我从它的good_ipv6.txt里借了几百ip放goproxy里就好了
好像啓用quic也可以用...
https://phuslu.github.io/gae.user.json 老大英明

感谢老大多年辛劳 开发可以停 多事之秋里人安全别出事就好

![capture](https://user-images.githubusercontent.com/32247328/31230864-d865823a-aa17-11e7-8a2d-b595ea1e50a8.PNG)

**Comment by wpyok500** [comment]
@phuslu  请问预计什么时候恢复goproxy项目。

**Comment by masktao** [comment]
作者没事就好

**Comment by mouseroser** [comment]
只要作者无事就好

**Comment by shujunwu** [comment]
@phuslu 
最好的问候！！！

**Comment by thundery1** [comment]
问候，问好！

**Comment by MEOWMEOWMOMODA** [comment]
@您好，请问可以给我发一份1623版本的goproxy么。
我的谷歌邮箱是heguohao94@gmail.com

**Comment by MEOWMEOWMOMODA** [comment]
@lndnxp 您好，请问可以给我发一份1623版本的goproxy么。
我的谷歌邮箱是heguohao94@gmail.com

**Comment by kang000feng** [comment]
感谢社长，非常不易！ 
@indnxp 您好，请问可以也给我发一份吗？谢谢！ 帐户名＋gmail邮箱

**Comment by out0fmemory** [comment]
@MEOWMEOWMOMODA M @kang000feng ka 可以在我这个镜像里边下载，release里边有；基于删项目前的最新代码编译
https://github.com/out0fmemory/Goproxy-Always-Available/releases

**Comment by lndnxp** [comment]
[https://github.com/goproxy0/goproxy/releases](https://github.com/goproxy0/goproxy/releases)

![default](https://user-images.githubusercontent.com/32247328/31603600-3ef8eacc-b293-11e7-911e-72ebef129f90.PNG)

感谢楼上 @out0fmemory

@MEOWMEOWMOMODA @kang000feng 

1. 解压[goproxy_windows_amd64-r1623.7z](https://github.com/goproxy0/goproxy/releases/download/r1623/goproxy_windows_amd64-r1623.7z)

2. [https://phuslu.github.io/gae.user.json](https://phuslu.github.io/gae.user.json)另存为gae.user.json放入解压文件夹

3. 搞定

**Comment by MEOWMEOWMOMODA** [comment]
@out0fmemory 谢谢老哥啦。已经下载好了

**Comment by mouseroser** [comment]
@out0fmemory <https://github.com/out0fmemory> 对了，mac下用哪个？

2017-10-16 17:44 GMT+08:00 MEOWMEOWMOMODA <notifications@github.com>:

**Comment by out0fmemory** [comment]
@mouseroser mac的系统代号是darwin，所以下载goproxy_darwin_amd64-r1625.tar.bz2这个
