### ISSUE TITLE
今天开始彻底封网了

### ISSUE THREAD

**Issue by mouseroser** [phuslu/phuslu.github.io#8]
上周用gscan_quic扫了1w个存货，今天开始少5k个地址个位数的存货。

**Comment by kirbyzhu** [comment]
不要危言耸听诶

**Comment by mouseroser** [comment]
现在是4w个，只扫到100个可用

2017-10-16 11:16 GMT+08:00 kirbyzhu <notifications@github.com>:

**Comment by mouseroser** [comment]
@kirbyzhu 

应该是十九大期间gw加强管控了，这几天又恢复了！！！
