### ISSUE TITLE
只有google搜索能用，其他网站都是下面的错误

### ISSUE THREAD

**Issue by out0fmemory** [phuslu/phuslu.github.io#9]
只有google搜索能用，其他网站都是下面的错误，开启quck，ip用的这个项目里的，这是神马情况？
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1625 (go/devel +b17470d Fri Oct 13 06:48:36 2017 +0000 darwin/amd64)",
    "filter": "*gae.Filter",
    "error": "unexpected EOF"
}

**Comment by 2378** [comment]
Goproxy-Always-Available
原以为你能扛起大旗

**Comment by kirbyzhu** [comment]
r1623 你怎么到r1625了啊 
我的1623正常

**Comment by out0fmemory** [comment]
@2378 @kirbyzhu 目前我镜像里的可以运行，之前不能运行是因为没有替换部署自己的服务端
1625应该是我改了洗readme导致提交次数变化

**Comment by out0fmemory** [comment]
开启quic，使用gscan_quic扫描到的ip还是可以用的，虽然速度不怎么好

**Comment by mouseroser** [comment]
@2378 @out0fmemory 
开启quic，使用gscan_quic扫描到的ip还是可以用的，速度还是可以的，只不过gw时不时的抽风

**Comment by kirbyzhu** [comment]
现在不行了，扫不到ip了
